"""Spec store: the YAML spec behind every AI-built dashboard, keyed by slug.

This is what makes "modify my dashboard" round-trip: load spec -> edit ->
recompile -> re-import (content-versioned uuids keep it an in-place update).

The table is created lazily with checkfirst instead of an alembic migration:
a fork-local migration would race upstream's migration heads on every
Superset release merge; a single additive table avoids that entirely.
"""
from __future__ import annotations

from flask_appbuilder import Model
from sqlalchemy import Column, DateTime, Integer, String, Text, func, inspect


class AiAnalystSpec(Model):
    __tablename__ = "ai_analyst_spec"

    id = Column(Integer, primary_key=True)
    slug = Column(String(255), unique=True, nullable=False)
    database_id = Column(Integer, nullable=False)
    spec_yaml = Column(Text, nullable=False)
    created_on = Column(DateTime, server_default=func.now())
    changed_on = Column(DateTime, server_default=func.now(), onupdate=func.now())


class AiAnalystChat(Model):
    """A saved conversation, private to one user.

    model_messages: the Anthropic message history (JSON), used to rehydrate
    the agent so a chat survives restarts. ui_transcript: exactly what the
    chat page renders (JSON list of message dicts), including final approval
    states.
    """

    __tablename__ = "ai_analyst_chat"

    id = Column(String(32), primary_key=True)  # uuid hex, generated by api.py
    user_id = Column(Integer, nullable=False, index=True)
    title = Column(String(255), nullable=False, default="New chat")
    model_messages = Column(Text, nullable=False, default="[]")
    ui_transcript = Column(Text, nullable=False, default="[]")
    created_on = Column(DateTime, server_default=func.now())
    changed_on = Column(DateTime, server_default=func.now(), onupdate=func.now())


def ensure_table() -> None:
    from superset.extensions import db

    insp = inspect(db.engine)
    for model in (AiAnalystSpec, AiAnalystChat):
        if not insp.has_table(model.__tablename__):
            model.__table__.create(db.engine, checkfirst=True)


def upsert_spec(slug: str, database_id: int, spec_yaml: str) -> None:
    from superset.extensions import db

    row = db.session.query(AiAnalystSpec).filter_by(slug=slug).one_or_none()
    if row is None:
        row = AiAnalystSpec(slug=slug, database_id=database_id,
                            spec_yaml=spec_yaml)
        db.session.add(row)
    else:
        row.database_id = database_id
        row.spec_yaml = spec_yaml
    db.session.commit()


def all_specs() -> dict[str, str]:
    from superset.extensions import db

    return {
        row.slug: row.spec_yaml
        for row in db.session.query(AiAnalystSpec).all()
    }


# ------------------------------------------------------------------- chats


def list_chats(user_id: int) -> list[dict]:
    from superset.extensions import db

    rows = (
        db.session.query(AiAnalystChat)
        .filter_by(user_id=user_id)
        .order_by(AiAnalystChat.changed_on.desc())
        .limit(100)
        .all()
    )
    return [
        {"id": r.id, "title": r.title,
         "changed_on": r.changed_on.isoformat() if r.changed_on else None}
        for r in rows
    ]


def load_chat(chat_id: str, user_id: int) -> AiAnalystChat | None:
    from superset.extensions import db

    return (
        db.session.query(AiAnalystChat)
        .filter_by(id=chat_id, user_id=user_id)
        .one_or_none()
    )


def save_chat(chat_id: str, user_id: int, title: str,
              model_messages: str, ui_transcript: str) -> None:
    from superset.extensions import db

    row = db.session.query(AiAnalystChat).filter_by(id=chat_id).one_or_none()
    if row is None:
        row = AiAnalystChat(id=chat_id, user_id=user_id, title=title)
        db.session.add(row)
    elif row.user_id != user_id:
        raise PermissionError("chat belongs to another user")
    row.title = title
    row.model_messages = model_messages
    row.ui_transcript = ui_transcript
    db.session.commit()


def delete_chat(chat_id: str, user_id: int) -> bool:
    from superset.extensions import db

    n = (
        db.session.query(AiAnalystChat)
        .filter_by(id=chat_id, user_id=user_id)
        .delete()
    )
    db.session.commit()
    return bool(n)
